#!/usr/bin/env bash

addgroup --system dalmatiner
adduser --system --home /var/lib/ddb --no-create-home --ingroup dalmatiner
chown -R dalmatiner:dalmatiner /var/lib/ddb
chown -R dalmatiner /var/log/ddb
