#!/bin/bash

# Sort out file permissions
if [[ $(id dalmatiner 2>/dev/null) ]] ;then
    chown -R dalmatiner:dalmatiner /var/lib/ddb
    chown -R dalmatiner:dalmatiner /var/log/ddb
fi

CONFFILE=/etc/ddb/ddb.conf

if [ ! -f "${CONFFILE}" ]
then
    echo "Creating new configuration from example file."
    cp ${CONFFILE}.example ${CONFFILE}
else
    echo "Please update your configuration according to the update manual!"
fi
