#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if [[ "x${SKIP}x" == "x1x" ]]
then
        exit 0
fi

make pre-commit
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
  echo "checks failed."
  exit 1
fi
